### PR TITLE
Distribute binary assets

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
## What

Release binary assets so that the developers don't need to close this repo and build it in their local env.

### CODE REVIEW

**Comment by ko28** [comment]
Aren't binary assets distributed through: `curl -LO https://storage.googleapis.com/spinnaker-artifacts/spin/$(curl -s https://storage.googleapis.com/spinnaker-artifacts/spin/latest)/linux/amd64/spin`? 

I think the process of building is an private Google Container Registry thing, there is probably a web hook listening to the latest git commits to master. This commit would do the same thing but on Github. Since this is a binary and not an image, I think distribution through Github makes more sense. 

On a side note, it would nice if `http://gcr.io/spinnaker-marketplace/spin` could be public, similar to how `http://gcr.io/spinnaker-marketplace/deck` is. Doesn't seem the latter has been update for a while. Does anyone who know maintains spinnaker-marketplace?

**Comment by kskewes-sf** [comment]
I'm a big fan of GoReleaser.

As we start to get on top of releases again I guess there are a couple of questions:
1. Do we publish binaries to GH or to [GCS](https://console.cloud.google.com/storage/browser/spinnaker-artifacts/spin?cloudshell=false&project=spinnaker-community) per [docs](https://spinnaker.io/docs/setup/other_config/spin/)?
2. Do we use GoReleaser or a mix of GHA as per the other Java services? See: https://github.com/spinnaker/spin/pull/329

Lastly, GCR is the old container registry and Spinnaker migrated to Google Artifact Registry ([GAR](https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/docker)) for https://spinnaker.io/changelogs/1.24.0-changelog/

**Comment by kskewes-sf** [comment]
Thanks again Keisuke. It's a shame we didn't get to progress this PR at the time. :(

https://github.com/spinnaker/spin/pull/329 has now merged as consolation. 

Latest binaries from `master` available here: https://console.cloud.google.com/storage/browser/spinnaker-artifacts/spin/master?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22,%22s%22:%5B(%22i%22:%22displayName%22,%22s%22:%221%22)%5D))&cloudshell=false&project=spinnaker-community&prefix=&forceOnObjectsSortingFiltering=false

Container images available here: https://console.cloud.google.com/artifacts/docker/spinnaker-community/us/docker/spin

```
$ docker run --rm -it us-docker.pkg.dev/spinnaker-community/docker/spin:master-latest
# spin --version
version master-95b72f7-202203180148
```

Will change the user to `spinnaker` from non-root to uid/gid 1000 or similar and make the entrypoint the `spin` binary but CI is now a go.

**Comment by KeisukeYamashita** [comment]
Thank you very much!

**Pull request closed without merging**
