### PR TITLE
fix(dockerfile): update Dockerfile base image

### PR DESCRIPTION
**Pull request by ShotaKitazawa**
go.mod is written `go 1.15`, but Dockerfile base image is `go:1.12`.
So that now, `docker build` command execution is failure.

```
$ docker build .
...
+ go build -ldflags '' .
# github.com/spinnaker/spin/cmd/gateclient
cmd/gateclient/client.go:201:10: undefined: "github.com/pkg/errors".Unwrap
cmd/gateclient/client.go:244:53: http.DefaultTransport.(*http.Transport).Clone undefined (type *http.Transport has no field or method Clone)
note: module requires Go 1.15
The command '/bin/sh -c ./build.sh --go-os linux --go-arch amd64 --version "${VERSION:-}"' returned a non-zero code: 2
```

### CODE REVIEW

**Comment by maker2413** [comment]
I was about to make my own PR for this. The Dockerfile is broken without this change merged in. Updating the base image to golang:1.15 fixes docker build.

**Comment by everops-alex** [comment]
can we get this caught up with `master` and merged please.

**Comment by everops-alex** [comment]
cc @lwander @KeisukeYamashita

**Review by Chinikins — APPROVED** [review]

**Review by Chinikins — COMMENTED** [review]
If you could change the PR title, this would then be ready for merge...

<type>(<scope>): <subject>

**Comment by ShotaKitazawa** [comment]
sorry. I have just changed title.

**Review by mattgogerly — APPROVED** [review]

**Pull request merged**
