### PR TITLE
chore(release): Updated client for spinnaker 1.22.0

### PR DESCRIPTION
**Pull request by german-muzquiz**
Gate client updated against Gate branch `release-1.22.x`, per the [contributing guidelines](https://github.com/spinnaker/spin/blob/master/CONTRIBUTING.md#updating-the-gate-api)

### CODE REVIEW

**Comment by Chinikins** [comment]
hey @german-muzquiz , could you take a look at https://github.com/spinnaker/spin/commit/29b753ed68ce539c0ecae6653989fa0bf1d0b8dd as that takes care of the build error. @kevinawoo would it make sense to merge those commits to this release branch?

**Comment by kevinawoo** [comment]
Yeah, I think but makes sense to pull those changes in

**Comment by Chinikins** [comment]
I opened this for the merge https://github.com/spinnaker/spin/pull/296 but I see https://github.com/spinnaker/gate/tree/release-1.22.x doesn't have https://github.com/spinnaker/gate/pull/1310

**Comment by german-muzquiz** [comment]
@Chinikins  This PR is addressed to `master` branch. Maybe I need to close this one and create another one, targeted to branch `release-1.22.x` after https://github.com/spinnaker/spin/pull/296#pullrequestreview-473790776 is merged?

**Comment by Chinikins** [comment]
Hmm, so I think what's happening here is Gate on 1.22 where it is currently creates a swagger build that breaks so it needs both the change that's on master branches already for spin and gate.

**Comment by Chinikins** [comment]
I also don't follow why the spinnaker 1.22 release has gate on 1.18? https://spinnaker.io/community/releases/versions/1-22-0-changelog#gate-1-18-0

**Comment by kevinawoo** [comment]
closing this PR since this is incorrectly pulling in 1.22 Gate into spin cli's master.

**Pull request closed without merging**
