### PR TITLE
chore(builds): Adds GHActions CI for PRs, master, and release branches.

### PR DESCRIPTION
**Pull request by ttomsu**
Followed basic layout from https://github.com/mvdan/github-actions-golang and pulled commands from prexisting Travis CI steps.

### CODE REVIEW

**Comment by ttomsu** [comment]
It appears to have worked on my fork: https://github.com/ttomsu/spin/runs/423852840?check_suite_focus=true

**Comment by louisjimenez** [comment]
Any reason to keep the Travis build files around after this?

**Comment by ttomsu** [comment]
If any releasing is done through Travis/Bintray, that hasn't been migrated yet. Otherwise, I'd keep them building in parallel for a week or two and then disable the Metal Travis build. GHA should be faster.

**Comment by louisjimenez** [comment]
Sounds good, created an issue for when it is ready, https://github.com/spinnaker/spinnaker/issues/5386

**Pull request merged**
