### PR TITLE
feat(execute): add individual parameter option

### PR DESCRIPTION
**Pull request by ethanfrogers**
adds an option to specify multiple key=value parameters instead of using
a parameter file. the default behavior is kept the same but if the user
passes `-p` instead, it will parse the arguments as key/value pairs.

### CODE REVIEW

**Comment by ethanfrogers** [comment]
Example usage:
```
$ spin pipeline execute --application app --name pipeline -p PARAM1=foo --parameter PARAM2=bar
```

**Comment by jan25** [comment]
My suggestion here - instead of having `-p` for each pair could we support all pairs in same argument?
E.g.` -p KEY1=VAL1;KEY2=VAL2`

Ideas?

**Comment by ethanfrogers** [comment]
@jan25 - thanks for the suggestion! What do you think would make that easier than repeated `-p` arguments? My reasoning for this approach was that it seems like a pretty common pattern among other CLI tools like `kubectl`.

**Comment by jan25** [comment]
Just something that seems reasonable while typing in the arguments for e.g. all pairs will be in one place as a single string. If its very common to type/allow repeated flags this PR looks fine :)

**Comment by ezimanyi** [comment]
I could be wrong `pflag` library may actually allow either `-p a=b,c=d` or `-p a=b -p c=d` (or some combination)...worth checking this!

**Comment by ethanfrogers** [comment]
Confirmed! `StringSliceVarP` accepts arguments in both forms - `-p a=b,b=c` or  `-p a=b -p b=c` [Docs for the curious](https://pkg.go.dev/github.com/spf13/pflag?tab=doc#StringSliceVar).

**Comment by Chinikins** [comment]
I opened a PR to document this change as well as some of the other changes added to the Spin CLI but I'm unsure how the documentation coordinates with Spin CLI release cycles.

**Comment by ezimanyi** [comment]
Right now we don't have versioned documentation, but that is on the [roadmap](https://github.com/spinnaker/governance/blob/master/rfc/website-revamp.md#goals) for the documentation SIG.  At this point we either note in the docs PR what version is needed when describing the feature, or wait until the feature is released to merge the docs change.

**Pull request merged**
