### PR TITLE
Upgrade Go to 1.16

### PR DESCRIPTION
**Pull request by KeisukeYamashita**
## What

Update the Go to 1.16 for application and in the CI

## Ref

* [Go 1.16 is released](https://blog.golang.org/go1.16)

### CODE REVIEW

**Review by Chinikins — APPROVED** [review]

**Comment by mbwhelan** [comment]
This change is also included in #319

**Review by mercury200Hg — COMMENTED** [review]
In go.mod line no 24, shouldn't `k8s.io/client-go v11.0.0+incompatible` be also changed to `k8s.io/client-go v0.21.2` ?
Just a thought, this usually gives an error when you use this project as golang module.

**Comment by ko28** [comment]
+1 from me, ran my PR https://github.com/spinnaker/spin/pull/322 using 1.16.6 linux/amd64 and all the tests passed fine.

**Comment by KeisukeYamashita** [comment]
This is a PR 7 month ago and the 1.7 has been released, I will close it

**Pull request closed without merging**
